#ifndef FS_SYSTEM_H
#define FS_SYSTEM_H

#define FS_SYSTEM_MAGIC_NUMBER (0xFF << 24) & ('F' << 16) & ('S' << 8) & (0xFF)
#define FS_SYSTEM_BLOCK_SECTOR_COUNT 1
#define FS_SYSTEM_START_SECTOR 1
#define FS_SYSTEM_SECTOR_COUNT 1024
#define FS_SYSTEM_INODE_COUNT 64

#define FS_BYTES_PER_SECTOR 512
#define FS_SYSTEM_BYTES_PER_BLOCK FS_SYSTEM_BLOCK_SECTOR_COUNT * FS_BYTES_PER_SECTOR

#endif
